name: mazeRunnerCore
version: '1.0-SNAPSHOT'
main: me.elec.mazerunnercore.MazeRunnerCore
api-version: '1.20'
load: STARTUP
commands:
  mazegame:
    description: Opens the Maze Game GUI.
    usage: /mazegame
    aliases: game
  spawn:
    description: Teleports you to the lobby.
    usage: /spawn
    aliases: lby
  leave:
    description: Teleports you to the lobby.
    usage: /leave
    aliases: quit
  leaderboard:
    description: View the leaderboard
    usage: /leaderboard <mazeName> <difficulty>
  reconnect:
    description: Toggles on/off of the auto-reconnect feature
    usage: /reconnect
    aliases: connect
  website:
    description: Shows the website
    usage: /website
    aliases: wb
  discord:
    description: Shows the discord
    usage: /discord
    aliases: dsc